[package]
name = "mdl-verifier"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Syfaro <syfaro@huefox.com>"]

[dependencies]
ciborium = "0.2.2"
eyre = "0.6.12"
hex = "0.4.3"
hex-literal = "0.4.1"
nfc1 = { version = "0.5.2", default-features = false }
rand = "0.9.0"
strum = { version = "0.27.1", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.14.0", features = ["v4"] }
